### ISSUE TITLE
Fix NavBar Profile button 

### ISSUE THREAD

**Issue by sngo103** [sngo103/QuickEatz#6]
The NavBar Profile button dropdown menu is stuck on open. It needs to be fixed so that it closes and opens when clicking on the profile icon.

Refer to the original code [here](https://tailwindui.com/preview) to try and replicate the original behavior and fix the issue.

**Comment by TDLorenz** [comment]
navbar profile pic closes and opens when clicked, however entering and leaving transitions have still not yet been implemented
